name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Run unit tests with Makefile
        run: |
          make test-xml

      - name: Publish Data Sender test results
        uses: dorny/test-reporter@v1
        if: always()  # Run even if tests fail
        with:
          name: Data Sender Core Test Results
          path: test-results-data-sender.xml
          reporter: java-junit
          fail-on-error: false  # Don't fail the job, let both test suites run

      - name: Publish Sensor Buffer test results
        uses: dorny/test-reporter@v1
        if: always()  # Run even if tests fail
        with:
          name: Sensor Buffer Core Test Results
          path: test-results-sensor-buffer.xml
          reporter: java-junit
          fail-on-error: false  # Don't fail the job, let both test suites run

      - name: Upload all test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results-data-sender.xml
            test-results-sensor-buffer.xml

      - name: Check if any tests failed
        run: |
          # Check if either test suite had failures
          data_sender_failures=$(grep -o 'failures="[0-9]*"' test-results-data-sender.xml | grep -o '[0-9]*' || echo "0")
          sensor_buffer_failures=$(grep -o 'failures="[0-9]*"' test-results-sensor-buffer.xml | grep -o '[0-9]*' || echo "0")
          
          total_failures=$((data_sender_failures + sensor_buffer_failures))
          
          echo "Data Sender failures: $data_sender_failures"
          echo "Sensor Buffer failures: $sensor_buffer_failures"
          echo "Total failures: $total_failures"
          
          if [ $total_failures -gt 0 ]; then
            echo "❌ $total_failures test(s) failed overall"
            exit 1
          else
            echo "✅ All tests passed!"
          fi