name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Run unit tests
        run: |
          gcc -I include/ main/data_sender_core.c test/test_data_sender_core.c -o test_core
          ./test_core test-results.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()  # Run even if tests fail
        with:
          name: Unit Test Results
          path: test-results.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml